"""empty message

Revision ID: d41ff2cc96f7
Revises: 5b23cfdca428
Create Date: 2025-10-06 15:32:40.945320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41ff2cc96f7'
down_revision: Union[str, Sequence[str], None] = '5b23cfdca428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'description')
    # ### end Alembic commands ###
